// OpenAPIGenerator.js - Génération de spécification OpenAPI depuis le trafic capturé
// PentestHAR - Reconstruction automatique d'API spec

class OpenAPIGenerator {
  constructor() {
    this.spec = null;
    this.endpoints = new Map(); // path -> methods -> details
  }

  // Générer la spec OpenAPI depuis les endpoints
  generate(endpoints, options = {}) {
    const baseUrl = options.baseUrl || this.detectBaseUrl(endpoints);
    const title = options.title || 'API Reconstructed by PentestHAR';

    this.spec = {
      openapi: '3.0.3',
      info: {
        title,
        description: 'Spécification OpenAPI générée automatiquement à partir du trafic réseau capturé.',
        version: '1.0.0',
        contact: {
          name: 'Generated by PentestHAR'
        }
      },
      servers: [
        {
          url: baseUrl,
          description: 'Serveur principal détecté'
        }
      ],
      paths: {},
      components: {
        securitySchemes: this.detectSecuritySchemes(endpoints),
        schemas: {}
      },
      tags: this.generateTags(endpoints)
    };

    // Grouper les endpoints par path normalisé
    const pathGroups = new Map();
    for (const ep of endpoints) {
      const path = this.convertToOpenAPIPath(ep.normalizedPath);
      if (!pathGroups.has(path)) {
        pathGroups.set(path, []);
      }
      pathGroups.get(path).push(ep);
    }

    // Générer les paths
    for (const [path, pathEndpoints] of pathGroups) {
      this.spec.paths[path] = this.generatePathItem(pathEndpoints);
    }

    return this.spec;
  }

  // Convertir un path normalisé en format OpenAPI
  convertToOpenAPIPath(normalizedPath) {
    return normalizedPath
      .replace(/\/{id}/g, '/{id}')
      .replace(/\/{uuid}/g, '/{uuid}')
      .replace(/\/{objectId}/g, '/{objectId}')
      .replace(/\/{hash}/g, '/{hash}');
  }

  // Détecter l'URL de base
  detectBaseUrl(endpoints) {
    if (endpoints.length === 0) return 'https://api.example.com';

    const hosts = {};
    for (const ep of endpoints) {
      hosts[ep.host] = (hosts[ep.host] || 0) + 1;
    }

    const topHost = Object.entries(hosts).sort((a, b) => b[1] - a[1])[0][0];
    return `https://${topHost}`;
  }

  // Détecter les schémas de sécurité
  detectSecuritySchemes(endpoints) {
    const schemes = {};
    let hasBearer = false;
    let hasApiKey = false;
    let hasCookie = false;

    for (const ep of endpoints) {
      for (const header of ep.parameters.header || []) {
        const name = header.name.toLowerCase();
        if (name === 'authorization') hasBearer = true;
        if (name.includes('api-key') || name.includes('apikey')) hasApiKey = true;
      }

      // Vérifier les cookies dans les requêtes
      // (simplifié - en réalité on regarderait les headers Cookie)
    }

    if (hasBearer) {
      schemes.bearerAuth = {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT'
      };
    }

    if (hasApiKey) {
      schemes.apiKeyAuth = {
        type: 'apiKey',
        in: 'header',
        name: 'X-API-Key'
      };
    }

    // Toujours ajouter cookie auth comme option
    schemes.cookieAuth = {
      type: 'apiKey',
      in: 'cookie',
      name: 'session'
    };

    return schemes;
  }

  // Générer les tags à partir des paths
  generateTags(endpoints) {
    const tagSet = new Set();

    for (const ep of endpoints) {
      const parts = ep.normalizedPath.split('/').filter(Boolean);
      if (parts.length > 0) {
        // Utiliser le premier segment comme tag
        const tag = parts[0].replace(/[{}]/g, '');
        if (tag && !tag.startsWith('v') && tag !== 'api') {
          tagSet.add(tag);
        } else if (parts.length > 1) {
          tagSet.add(parts[1].replace(/[{}]/g, ''));
        }
      }
    }

    return Array.from(tagSet).map(name => ({
      name,
      description: `Opérations liées à ${name}`
    }));
  }

  // Générer un path item (toutes les méthodes pour un path)
  generatePathItem(endpoints) {
    const pathItem = {};

    // Extraire les paramètres de path
    const pathParams = this.extractPathParameters(endpoints[0].normalizedPath);

    for (const ep of endpoints) {
      const method = ep.method.toLowerCase();
      pathItem[method] = this.generateOperation(ep, pathParams);
    }

    return pathItem;
  }

  // Extraire les paramètres de path
  extractPathParameters(path) {
    const params = [];
    const matches = path.match(/\{([^}]+)\}/g) || [];

    for (const match of matches) {
      const name = match.replace(/[{}]/g, '');
      params.push({
        name,
        in: 'path',
        required: true,
        schema: this.inferPathParamSchema(name),
        description: `Identifiant ${name}`
      });
    }

    return params;
  }

  // Inférer le schéma d'un paramètre de path
  inferPathParamSchema(name) {
    if (name === 'id') {
      return { type: 'integer', format: 'int64', example: 123 };
    }
    if (name === 'uuid') {
      return { type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000' };
    }
    if (name === 'objectId') {
      return { type: 'string', pattern: '^[a-f0-9]{24}$', example: '507f1f77bcf86cd799439011' };
    }
    if (name === 'hash') {
      return { type: 'string', pattern: '^[a-f0-9]{32}$' };
    }
    return { type: 'string' };
  }

  // Générer une opération
  generateOperation(endpoint, pathParams) {
    const operation = {
      summary: this.generateSummary(endpoint),
      description: this.generateDescription(endpoint),
      operationId: this.generateOperationId(endpoint),
      tags: this.getTagsForEndpoint(endpoint),
      parameters: [...pathParams],
      responses: this.generateResponses(endpoint)
    };

    // Ajouter les query parameters
    for (const param of endpoint.parameters.query || []) {
      operation.parameters.push({
        name: param.name,
        in: 'query',
        required: false,
        schema: this.inferSchema(param.value, param.type),
        example: param.value
      });
    }

    // Ajouter le request body pour POST/PUT/PATCH
    if (['POST', 'PUT', 'PATCH'].includes(endpoint.method)) {
      const bodyParams = endpoint.parameters.body || [];
      if (bodyParams.length > 0) {
        operation.requestBody = this.generateRequestBody(bodyParams);
      }
    }

    // Ajouter la sécurité si auth détectée
    if (endpoint.parameters.header?.some(h =>
      h.name.toLowerCase() === 'authorization' ||
      h.name.toLowerCase().includes('api-key')
    )) {
      operation.security = [{ bearerAuth: [] }];
    }

    // Marquer comme IDOR candidate si applicable
    if (endpoint.idorIndicators && endpoint.idorIndicators.length > 0) {
      operation['x-idor-candidate'] = true;
      operation['x-idor-confidence'] = Math.max(...endpoint.idorIndicators.map(i => i.confidence));
    }

    return operation;
  }

  // Générer un résumé pour l'opération
  generateSummary(endpoint) {
    const method = endpoint.method;
    const resource = this.extractResourceName(endpoint.normalizedPath);

    const verbs = {
      GET: 'Récupérer',
      POST: 'Créer',
      PUT: 'Mettre à jour',
      PATCH: 'Modifier partiellement',
      DELETE: 'Supprimer'
    };

    return `${verbs[method] || method} ${resource}`;
  }

  // Extraire le nom de la ressource du path
  extractResourceName(path) {
    const parts = path.split('/').filter(p => p && !p.startsWith('{'));
    if (parts.length === 0) return 'ressource';

    // Prendre le dernier segment non-paramétrique
    let resource = parts[parts.length - 1];

    // Singulariser si nécessaire
    if (resource.endsWith('s') && !resource.endsWith('ss')) {
      resource = resource.slice(0, -1);
    }

    return resource;
  }

  // Générer une description
  generateDescription(endpoint) {
    let desc = `Endpoint: ${endpoint.method} ${endpoint.originalPath}\n`;
    desc += `Requêtes observées: ${endpoint.requestCount || 1}\n`;

    if (endpoint.idorIndicators?.length > 0) {
      desc += `\n⚠️ **Candidat IDOR détecté** - Confiance: ${(Math.max(...endpoint.idorIndicators.map(i => i.confidence)) * 100).toFixed(0)}%`;
    }

    return desc;
  }

  // Générer un operationId unique
  generateOperationId(endpoint) {
    const method = endpoint.method.toLowerCase();
    const parts = endpoint.normalizedPath
      .split('/')
      .filter(p => p && !p.startsWith('{'))
      .map(p => p.charAt(0).toUpperCase() + p.slice(1));

    return method + parts.join('');
  }

  // Obtenir les tags pour un endpoint
  getTagsForEndpoint(endpoint) {
    const parts = endpoint.normalizedPath.split('/').filter(Boolean);
    for (const part of parts) {
      if (!part.startsWith('{') && !part.startsWith('v') && part !== 'api') {
        return [part];
      }
    }
    return ['default'];
  }

  // Inférer le schéma d'une valeur
  inferSchema(value, typeHint) {
    if (typeHint === 'integer') {
      return { type: 'integer', example: parseInt(value) || 0 };
    }
    if (typeHint === 'float') {
      return { type: 'number', format: 'float', example: parseFloat(value) || 0.0 };
    }
    if (typeHint === 'boolean') {
      return { type: 'boolean', example: value === 'true' };
    }
    if (typeHint === 'uuid') {
      return { type: 'string', format: 'uuid', example: value };
    }
    if (typeHint === 'email') {
      return { type: 'string', format: 'email', example: value };
    }
    if (typeHint === 'url') {
      return { type: 'string', format: 'uri', example: value };
    }
    if (typeHint === 'array') {
      return { type: 'array', items: { type: 'string' } };
    }

    // Par défaut: string
    return { type: 'string', example: value };
  }

  // Générer le request body
  generateRequestBody(bodyParams) {
    const properties = {};
    const required = [];

    for (const param of bodyParams) {
      const name = param.name.replace('[]', '');

      // Gérer les propriétés imbriquées
      if (param.name.includes('.')) {
        // Simplifier - juste ajouter la propriété racine
        const rootName = param.name.split('.')[0];
        properties[rootName] = { type: 'object' };
      } else if (param.name.endsWith('[]')) {
        properties[name] = {
          type: 'array',
          items: this.inferSchema(param.value, param.type)
        };
      } else {
        properties[name] = this.inferSchema(param.value, param.type);
      }
    }

    return {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties,
            required: required.length > 0 ? required : undefined
          }
        }
      }
    };
  }

  // Générer les réponses
  generateResponses(endpoint) {
    return {
      '200': {
        description: 'Réponse réussie',
        content: {
          'application/json': {
            schema: {
              type: 'object'
            }
          }
        }
      },
      '400': {
        description: 'Requête invalide'
      },
      '401': {
        description: 'Non authentifié'
      },
      '403': {
        description: 'Accès refusé'
      },
      '404': {
        description: 'Ressource non trouvée'
      },
      '500': {
        description: 'Erreur serveur'
      }
    };
  }

  // Exporter en YAML
  toYAML() {
    if (!this.spec) return '';
    return this.jsonToYaml(this.spec);
  }

  // Exporter en JSON
  toJSON(pretty = true) {
    if (!this.spec) return '';
    return pretty ? JSON.stringify(this.spec, null, 2) : JSON.stringify(this.spec);
  }

  // Conversion JSON vers YAML simple
  jsonToYaml(obj, indent = 0) {
    const spaces = '  '.repeat(indent);
    let yaml = '';

    if (Array.isArray(obj)) {
      for (const item of obj) {
        if (typeof item === 'object' && item !== null) {
          yaml += `${spaces}-\n`;
          yaml += this.jsonToYaml(item, indent + 1);
        } else {
          yaml += `${spaces}- ${this.formatYamlValue(item)}\n`;
        }
      }
    } else if (typeof obj === 'object' && obj !== null) {
      for (const [key, value] of Object.entries(obj)) {
        if (value === undefined) continue;

        if (typeof value === 'object' && value !== null) {
          if (Array.isArray(value) && value.length === 0) {
            yaml += `${spaces}${key}: []\n`;
          } else if (Object.keys(value).length === 0) {
            yaml += `${spaces}${key}: {}\n`;
          } else {
            yaml += `${spaces}${key}:\n`;
            yaml += this.jsonToYaml(value, indent + 1);
          }
        } else {
          yaml += `${spaces}${key}: ${this.formatYamlValue(value)}\n`;
        }
      }
    }

    return yaml;
  }

  // Formatter une valeur pour YAML
  formatYamlValue(value) {
    if (value === null) return 'null';
    if (value === true) return 'true';
    if (value === false) return 'false';
    if (typeof value === 'number') return String(value);
    if (typeof value === 'string') {
      // Échapper si nécessaire
      if (value.includes(':') || value.includes('#') || value.includes('\n') ||
        value.startsWith('{') || value.startsWith('[') || value.startsWith('"') ||
        value.startsWith("'") || value === '' || /^[\d.]+$/.test(value)) {
        return `"${value.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
      }
      return value;
    }
    return String(value);
  }

  // Générer le fichier complet avec commentaires
  generateWithComments(endpoints, options = {}) {
    const spec = this.generate(endpoints, options);

    let output = `# OpenAPI Specification - Generated by PentestHAR
#
# Cette spécification a été générée automatiquement à partir
# du trafic réseau capturé. Elle peut nécessiter des ajustements.
#
# IDOR Candidates sont marqués avec x-idor-candidate: true
#
# Date: ${new Date().toISOString()}
# Endpoints: ${endpoints.length}
#

`;
    output += this.toYAML();

    return output;
  }
}

// Export global pour Firefox extension
if (typeof window !== 'undefined') {
  window.OpenAPIGenerator = OpenAPIGenerator;
}
